### ISSUE TITLE
Unable to enable crypto on TCP connection 

### ISSUE THREAD

**Issue by pprw** [omeka-s-modules/Osii#10]
On some https Omeka S, I have this error when trying to import content with Osii.

Is it a issue on the web host or inside Osii? 

```
Omeka S a rencontré une erreur

Laminas\Http\Client\Adapter\Exception\RuntimeException
Unable to enable crypto on TCP connection corpus.louvre.fr: make sure the "sslcafile" or "sslcapath" option are properly set for the environment.

Détails :

ErrorException: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A000152:SSL routines::unsafe legacy renegotiation disabled in /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-http/src/Client/Adapter/Socket.php:397
Stack trace:
#0 [internal function]: Laminas\Stdlib\ErrorHandler::addError()
#1 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-http/src/Client/Adapter/Socket.php(397): stream_socket_enable_crypto()
#2 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-http/src/Client/Adapter/Socket.php(355): Laminas\Http\Client\Adapter\Socket->enableCryptoTransport()
#3 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-http/src/Client.php(1465): Laminas\Http\Client\Adapter\Socket->connect()
#4 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-http/src/Client.php(965): Laminas\Http\Client->doRequest()
#5 /home/pwillaime/sites/heuristomeka/modules/Osii/src/Api/Adapter/OsiiImportAdapter.php(154): Laminas\Http\Client->send()
#6 /home/pwillaime/sites/heuristomeka/modules/Osii/src/Api/Adapter/OsiiImportAdapter.php(113): Osii\Api\Adapter\OsiiImportAdapter->doApiRequest()
#7 /home/pwillaime/sites/heuristomeka/modules/Osii/src/Api/Adapter/OsiiImportAdapter.php(93): Osii\Api\Adapter\OsiiImportAdapter->rootEndpointIsValid()
#8 /home/pwillaime/sites/heuristomeka/application/src/Api/Adapter/AbstractEntityAdapter.php(646): Osii\Api\Adapter\OsiiImportAdapter->validateEntity()
#9 /home/pwillaime/sites/heuristomeka/application/src/Api/Adapter/AbstractEntityAdapter.php(346): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity()
#10 /home/pwillaime/sites/heuristomeka/application/src/Api/Manager.php(224): Omeka\Api\Adapter\AbstractEntityAdapter->create()
#11 /home/pwillaime/sites/heuristomeka/application/src/Api/Manager.php(78): Omeka\Api\Manager->execute()
#12 /home/pwillaime/sites/heuristomeka/application/src/Mvc/Controller/Plugin/Api.php(99): Omeka\Api\Manager->create()
#13 /home/pwillaime/sites/heuristomeka/modules/Osii/src/Controller/Admin/ImportController.php(44): Omeka\Mvc\Controller\Plugin\Api->create()
#14 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Osii\Controller\Admin\ImportController->addAction()
#15 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#16 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#17 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil()
#18 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch()
#19 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch()
#20 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#21 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil()
#22 /home/pwillaime/sites/heuristomeka/index.php(21): Laminas\Mvc\Application->run()
#23 {main}

Next Laminas\Http\Client\Adapter\Exception\RuntimeException: Unable to enable crypto on TCP connection corpus.louvre.fr: make sure the "sslcafile" or "sslcapath" option are properly set for the environment. in /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-http/src/Client/Adapter/Socket.php:426
Stack trace:
#0 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-http/src/Client/Adapter/Socket.php(355): Laminas\Http\Client\Adapter\Socket->enableCryptoTransport()
#1 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-http/src/Client.php(1465): Laminas\Http\Client\Adapter\Socket->connect()
#2 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-http/src/Client.php(965): Laminas\Http\Client->doRequest()
#3 /home/pwillaime/sites/heuristomeka/modules/Osii/src/Api/Adapter/OsiiImportAdapter.php(154): Laminas\Http\Client->send()
#4 /home/pwillaime/sites/heuristomeka/modules/Osii/src/Api/Adapter/OsiiImportAdapter.php(113): Osii\Api\Adapter\OsiiImportAdapter->doApiRequest()
#5 /home/pwillaime/sites/heuristomeka/modules/Osii/src/Api/Adapter/OsiiImportAdapter.php(93): Osii\Api\Adapter\OsiiImportAdapter->rootEndpointIsValid()
#6 /home/pwillaime/sites/heuristomeka/application/src/Api/Adapter/AbstractEntityAdapter.php(646): Osii\Api\Adapter\OsiiImportAdapter->validateEntity()
#7 /home/pwillaime/sites/heuristomeka/application/src/Api/Adapter/AbstractEntityAdapter.php(346): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity()
#8 /home/pwillaime/sites/heuristomeka/application/src/Api/Manager.php(224): Omeka\Api\Adapter\AbstractEntityAdapter->create()
#9 /home/pwillaime/sites/heuristomeka/application/src/Api/Manager.php(78): Omeka\Api\Manager->execute()
#10 /home/pwillaime/sites/heuristomeka/application/src/Mvc/Controller/Plugin/Api.php(99): Omeka\Api\Manager->create()
#11 /home/pwillaime/sites/heuristomeka/modules/Osii/src/Controller/Admin/ImportController.php(44): Omeka\Mvc\Controller\Plugin\Api->create()
#12 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Osii\Controller\Admin\ImportController->addAction()
#13 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#14 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#15 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil()
#16 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch()
#17 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch()
#18 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#19 /home/pwillaime/sites/heuristomeka/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil()
#20 /home/pwillaime/sites/heuristomeka/index.php(21): Laminas\Mvc\Application->run()
#21 {main}


```

**Comment by jimsafley** [comment]
This is not an error in Osii. It looks like the remote server does not support RFC 5746 secure renegotiation. For this to work, you or a server administrator will need to enable insecure legacy renegotiation following [these directions](https://support.axway.com/kb/182365/language/en).

**Comment by pprw** [comment]
Thanks Jim and sorry to not have answered to the first reply. I will point administrators to this thread if needed.
