### ISSUE TITLE
Error on install v1.0.0 : Plural rule of merging text domain is not compatible with the current one

### ISSUE THREAD

**Issue by guitrottier** [omeka-s-modules/Osii#4]
Greetings,

Testing with the module (great!) I get this error when installing v1.0.0.

- Omeka S v3.2.1

Regards,

```
Laminas\I18n\Exception\RuntimeException
Plural rule of merging text domain is not compatible with the current one

Détails :


Laminas\I18n\Exception\RuntimeException: Plural rule of merging text domain is not compatible with the current one in /vendor/laminas/laminas-i18n/src/Translator/TextDomain.php:100
Stack trace:
#0 /vendor/laminas/laminas-i18n/src/Translator/Translator.php(705): Laminas\I18n\Translator\TextDomain->merge(Object(Laminas\I18n\Translator\TextDomain))
#1 /vendor/laminas/laminas-i18n/src/Translator/Translator.php(616): Laminas\I18n\Translator\Translator->loadMessagesFromPatterns('default', 'fr')
#2 /vendor/laminas/laminas-i18n/src/Translator/Translator.php(440): Laminas\I18n\Translator\Translator->loadMessages('default', 'fr')
#3 /vendor/laminas/laminas-i18n/src/Translator/Translator.php(355): Laminas\I18n\Translator\Translator->getTranslatedMessage('Email', 'fr', 'default')
#4 /application/src/I18n/Translator.php(25): Laminas\I18n\Translator\Translator->translate('Email', 'default', 'fr')
#5 /vendor/laminas/laminas-mvc-i18n/src/Translator.php(71): Omeka\I18n\Translator->translate('Email', 'default', NULL)
#6 /vendor/laminas/laminas-i18n/src/View/Helper/Translate.php(37): Laminas\Mvc\I18n\Translator->translate('Email', 'default', NULL)
#7 /application/view/omeka/admin/user/browse.phtml(10): Laminas\I18n\View\Helper\Translate->__invoke('Email')
#8 /vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/home/aadckuxc/...')
#9 /vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#10 /vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#11 /vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#12 /vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#13 /vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#14 /vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#15 /vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#16 /vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#17 /index.php(21): Laminas\Mvc\Application->run()
#18 {main}
```

**Comment by jimsafley** [comment]
Thanks for bringing this to our attention. It should be fixed in the newly published version ([1.0.1](https://github.com/omeka-s-modules/Osii/releases/tag/v1.0.1)).
