### ISSUE TITLE
Error: Class "OmekaSItemImporter/Module" not found

### ISSUE THREAD

**Issue by wsu-lp** [omeka-s-modules/Osii#6]
I started a vanilla installation of Omeka S 4.0.1.  I'm trying to install the Omeka S Item Importer module, but I get this error when I attempt to install the module.  I'm not sure if my installation is missing requirements or something else.  Any advice is welcome. 

`2023-03-22T00:17:01+00:00 ERR (3): Error: Class "OmekaSItemImporter\Module" not found in /var/www/html/application/src/Module/Manager.php:354
Stack trace:
#0 /var/www/html/application/src/Module/Manager.php(225): Omeka\Module\Manager->getModuleObject(Object(Omeka\Module\Module))
#1 /var/www/html/application/src/Controller/Admin/ModuleController.php(117): Omeka\Module\Manager->install(Object(Omeka\Module\Module))
#2 /var/www/html/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Omeka\Controller\Admin\ModuleController->installAction()
#3 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#4 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#5 /var/www/html/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#6 /var/www/html/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#7 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#8 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#9 /var/www/html/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#10 /var/www/html/index.php(21): Laminas\Mvc\Application->run()
#11 {main}`

**Comment by wsu-lp** [comment]
I was using the Easy Admin module to install Omeka S Item Importer.  When I downloaded the OSII module and installed it manually it installed as expected.  The issue seems to be with the Easy Admin module and the version of the module it's installing.
